name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout Success
        run: ls -l

    steps:
      - name: Nexus Push
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://18.207.100.59:8081/
          username: admin
          password: ${{secrets.password}}
          format: raw
          repository: wheels
          assets: extension=zip
          filename: package.json
